# Generated by Django 5.0.3 on 2024-05-28 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Calories',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='FoodID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Datetime',
        ),
        migrations.AddField(
            model_name='food',
            name='search_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
