# Generated by Django 5.0.3 on 2024-05-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_rename_calories_food_calories_rename_foodid_food_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Parametres',
            fields=[
                ('ParametresID', models.AutoField(primary_key=True, serialize=False)),
                ('Sex', models.IntegerField()),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Goal', models.IntegerField()),
                ('Activity', models.IntegerField()),
                ('DateTime', models.DateField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.authentication')),
            ],
        ),
    ]
