# Generated by Django 5.0.3 on 2024-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_alter_food_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.CharField(default=11, max_length=40),
            preserve_default=False,
        ),
    ]
