# Generated by Django 5.0.3 on 2025-03-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_food_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='fat',
        ),
    ]
