# Generated by Django 5.0.3 on 2025-03-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_remove_food_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='UserID',
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.authentication'),
            preserve_default=False,
        ),
    ]
