# Generated by Django 5.0.3 on 2025-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0009_alter_food_user_userparametres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
