# Generated by Django 5.0.3 on 2025-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0010_food_carbohydrates_food_fat_food_fiber_food_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparametres',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
