# Generated by Django 5.0.3 on 2025-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_weightentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparametres',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
