# Generated by Django 5.0.3 on 2025-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_userparametres_target_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
