# Generated by Django 5.0.3 on 2025-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0014_alter_weightentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparametres',
            name='calories_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
