# Generated by Django 5.0.3 on 2025-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0015_userparametres_calories_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='portion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
